### ISSUE TITLE
User input data required for assets & algorithms

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/pm#106]
We need to be able to support:
 - assets that require some input data from the consumer
 - during C2D, some algorithms may require additional parameters from the consumer

Proposal:

- during publish, for every asset , for every service, the publisher can define a list of fields that needs to be filled by the consumer
- during publish, for algorithms, the publisher can define a list of fields that needs to be filled by the consumer

The fields are going to be stored in the ddo, under services.attributes.userdata using the following structure:
```json
[
   {
       "name":"surname",
        "type": "text",
        "label": "Name",
        "required": true,
       "description":"Please fill your name"
    },
   {
       "name":"age",
        "type": "number",
        "label": "Age",
        "required": false,
        "description":"Please fill your age"
    },
   {
       "name":"developer",
        "type": "boolean",
        "label": "Developer",
        "required": false,
        "description":"Are you a developer?"
    },
    {
       "name":"interval",
        "type": "select",
        "label": "Date",
        "required": false,
        "options": [
             {
                    "option1" : "Option number 1"
             }, 
             {
                  "option2" : "Option number 2"
             }
        ],
        "description": "Are you a developer?"
    },
]
```

For algorithm fields, we use the same concept, but they are stored in services.attributes.algodata using the following structure:

**Comment by alexcos20** [comment]
looks like mPowered will apply for a grant to push this into market

**Comment by trentmc** [comment]
Update: mPowered applied for and got the grant. [Here's](https://port.oceanprotocol.com/t/first-class-integration-with-parameters-to-c2d-in-ocean-market/1421) the forum post. They are proceeding.

**Comment by calina-c** [comment]
@AnaLoznianu propose to close.

**Comment by AnaLoznianu** [comment]
@trentmc mPowered got the grant in round 14. So far, there are no PRs on our components for this. 
I did notice they provided a link: https://github.com/mPowered-io/market/tree/v4-parameters, but it's not accessible. We should sync with them, now that V4 is so close to the release. They can proceed and start PRs against Ocean components

**Comment by AnaLoznianu** [comment]
I took this up. Synced with @idiom-bytes and started the discussions with the mPowered team to see how we can proceed after the V4 release
