### ISSUE TITLE
Human Readable URLs

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/pm#117]
From a marketing and branding perspective it would be great if we could implement human readable URLs.

At the moment publishers have to share very ugly looking URLs when they are promoting their datasets, for example:

[https://market.oceanprotocol.com/asset/did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38](https://market.oceanprotocol.com/asset/did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38)

For the publishers it would be better if they could set their own URL slug. For example: 

[https://market.oceanprotocol.com/asset/dataunion](https://market.oceanprotocol.com/asset/did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38)

This would require us to have a mapping between the domain slugs and the dids. It will also require us running a check to see if the slug is unique when the publisher sets it.

**Comment by calina-c** [comment]
Details to hash out:
- what we allow as a slug (e.g. obviously not something that starts with did:op:, something unique, does not contain special characters etc.)
- is there any case where we would have duplicate names? e.g. in theory we could have the same slug if on different chains, but that would be cumbersome to maintain
- will this reflect inside Aquarius/ES as part of the metadata structure, or would it be a simple mapping on frontend (or frontend-ish level)?
- scope and redirects: if we currently build this asset URL somewhere, it will need to be adapted with the slug logic. Is it possible to do this asynchronously on different components?

**Comment by TimDaub** [comment]
What about ENS names that point to a data token address? E.g. /asset/dataunion.eth or /asset/trepel.eth or whatever the user decides they like.

**Comment by kremalicious** [comment]
Something came out of prototyping and we accidentally created decentralized publisher URLs in the market which also covers human readable URLs. For the publisher, not the dataset but can't have everything 😄 

See https://github.com/oceanprotocol/market/issues/858#issuecomment-921725530

**Comment by jamiehewitt15** [comment]
@kremalicious The ENS names work great in the URLs for the profile pages. I can see that there could be a route to doing the same thing for assets in V4. If the asset URL points to the address of the asset NFT then the publisher would have the option to customise the asset URL with ENS

**Comment by kremalicious** [comment]
not gonna happen in v4 release, we have bigger things to do
