### ISSUE TITLE
Check vulnerabilities on the smart contracts

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/pm#136]
Besides solidity code audits. Run tools like https://github.com/crytic/slither & https://github.com/crytic/echidna with github actions to check for vulnerabilities in the smart contract code and deployed smart contracts
PS: I’ve heard good things about MythX as well but it’s a paid tool.

**Comment by DMats** [comment]
Slither recently added SARIF support, which allows Slither to report issues through the Github code scanning app.  An official Github action is not yet released but was teased in the [0.8.1 release notes](https://github.com/crytic/slither/releases/tag/0.8.1).

I found [this issue](https://github.com/crytic/slither/issues/948) asking for the status of the official Slither Github action, but no response from the maintainers has been given.

From there, I saw that @htadashi had created their own [Slither Github action](https://github.com/defibasket/defibasket-contracts/blob/main/.github/workflows/codeql-analysis.yml).  I will copy this and see if I can get it working.

**Comment by DMats** [comment]
Thanks for the info @htadashi!

**Comment by DMats** [comment]
Since https://github.com/oceanprotocol/contracts/pull/500 is merged, I'm closing this issue.

We briefly discussed using echidna, but ultimately chose to favor the fuzzing being implemented in ocean.py https://github.com/oceanprotocol/ocean.py/pull/726
