### ISSUE TITLE
Add manual image upload to our data NFT minting for V4

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/pm#160]
@AnaLoznianu commented on [Thu May 26 2022](https://github.com/oceanprotocol/market/issues/1477)

Add manual image upload to our data NFT minting for V4 (next to our default waves-artwork-set).

Could be something nice for everyone to try out the Ocean Market, minting "your own dataNFT as profile pic" for fun, caring about further functionality/ opportunities later, like creating datatoken (or adding features/to data unions/services we build/3rd party services/). 

Creating this mostly for discussions...

---

@mihaisc commented on [Thu May 26 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1138269604)

There are already ideas for using data nft as credentials or as profile . In first case you have the nft you have access to something. In second you use the data nft to store your profile data (it can be used as an alternative to ens )

---

@malvonme commented on [Mon May 30 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1141254912)

Hi all,
Hi @AnaLoznianu,

thank you for raising this to the market team!

This is meant as a potential low-effort test-balloon, feeling the water of what people, developers, builders actually can and want to do with our data NFT, "flavors" of how to create data supply (and demand), deriving further features from there (user centric design).

It could serve for several purposes:
A) Pimping the data NFT you mint as a pass-on-asset (e.g. in case you mint it for someone else, like an artist/musician)
B) Create 1 data NFT baseIP for your project, or NFT club, as an owner, and "brand" it right away (user love/endorsement)
C) Experiment with first limited NFT editions that include early data functionality, creating opportunity now, building on it later.

I compiled a lil bootleg post on this (content in sync with Trent):
https://mirror.xyz/cryptowally.eth/cl0azXM44ndABXhoHsJY0PWJdew2GD63j6um9-FmFqk

---

@malvonme commented on [Mon May 30 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1141265895)

PS:
If NFT is still new/unrelateable to you, maybe you like this (NFT profile pic trend in a nutshell): https://mirror.xyz/cryptowally.eth/YkaO0vPgwzzaYsZft7ONTmqURVwzgG2iCtjGj3Wxsxk

---

@malvonme commented on [Mon May 30 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1141290073)

A community member just made a graphic, giving you the fastest way to the concept/idea
https://twitter.com/AquaNauxt/status/1531296780687749124?s=20&t=1Jnqt3Ch7KuJ7pv6H3f8Yg

![FUBCSTJXoAAxP3k](https://user-images.githubusercontent.com/101562291/171025022-175c59bc-e616-48bb-803d-2d8a4c52ec70.jpeg)

---

@AnaLoznianu commented on [Tue Jul 05 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1174743092)

This is already possible by overriding the tokenURI. There are published assets with custom images: https://market.oceanprotocol.com/asset/did:op:39b9fa755de838a1a912e8589f64ce1601157cc2f1418ee9a3e77b7c7342f986 
so for now, we will not focus our efforts in this direction.

---

@malvonme commented on [Tue Jul 05 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1174851645)

I understand.

Just for some context:
The goal behind this was to increase actionability of the data we collect (and collect more data overall), not just an image to the data NFT, in a seamless manner. 

Seamless as in: "bring the data to the user, have the users carry their new data-store to the platforms". 

Like: have the data that you supply (write user settings/parameter) as a platform closest possible to the data you CONSUME (read additional settings/parameters stored by other platforms "through" my data NFT). It was supposed to be a early fun test (mint "your" NFT as data NFT), and by that, as a trojan horse, a complementary move to our current strategy of "build the market and wait for supply and demand, incentivize demand".

But as said: I understand if this is no priority. 

Thanks for considering, Ana.

---

@malvonme commented on [Wed Jul 06 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1176012249)

User request:
https://discord.com/channels/612953348487905282/612953349003673629/994173261464219668

---

@kremalicious commented on [Wed Jul 06 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1176129886)

1. Build a landing page reading out user's Data NFTs
2. Allow updating of selected NFT metadata, here `image` or `image_data` key within `tokenURI`, via ocean.js `nft.setMetadata()`
3. Go to Ocean DAO, ask for funds
4. Fun and profit

This utility file might be good place to start to see what one would need: https://github.com/oceanprotocol/market/blob/main/src/@utils/nft.ts

---

@malvonme commented on [Wed Jul 06 2022](https://github.com/oceanprotocol/market/issues/1477#issuecomment-1176216746)

Awesome @kremalicious, thank you!! Will insta-share with community

**Comment by w1kke** [comment]
How is it going to be taken care of that users will not upload existing NFTs that might be worth a ton and then selling their DataNFTs as copies of these NFTs?
Or is this no concern?

**Comment by mihaisc** [comment]
Sorry @w1kke not sure i understand what you are trying to say, can you please rephrase it.

**Comment by w1kke** [comment]
What if people upload images of Bored Ape Yacht Club NFTs or Crypto Punks - this will cause confusion with newbies who might not understand the concept of NFTs.

**Comment by mihaisc** [comment]
That's true. At a stack level we can't control that, people can do whatever they want, it's decentralized. This is why we don't really see the need to develop and enable this in our market. The focus of dataNFT is data , not the image. I think we are of the same mind here :)

**Comment by malvonme** [comment]
Alright, @mihaisc, @w1kke, good. So let's not build it. Thanks.

**Comment by w1kke** [comment]
@malvonme I would not have to care much or get involved really, I am doing that because I care. I get the feeling you are misunderstanding my intentions. I see this as my duty as an Ocean Protocol ecosystem member to raise my concerns where they come up. A collective of yes-men is not beneficial.

**Comment by malvonme** [comment]
I removed myself from this discussion. Thank you.
