### ISSUE TITLE
Gaia-X compliant Self Description

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#161]
Implement GX-compliant Self-Descriptions for data assets, participants and self-descriptions (Catalogue functionality).

The metadata needs to be extended or at least modified to allow the storage and retrieval of (additional) GX-compliant service self-descriptions. This can be done through additional fields directly queried via API.
This is mandatory for driving adoption in GX.
The catalogue must be able to store signed self-descriptions and VCs. Otherwise, Ocean can not be used in any Gaia-X ecosystem.
See: https://gitlab.com/gaia-x/lab/wiki/-/blob/main/Participant-SD-for-Architecture-Document-(WIP).md & https://compliance.gaia-x.eu/api/ 

Source: DeltaDAO

**Comment by kaimeinke** [comment]
The service provider side has already to a very large port been implemented as an MVP that can be discovered here: https://portal.minimal-gaia-x.eu/

This includes Service Self-Descriptions are visible in the frontend and are automatically submitted to the compliance service and checked in real-time: https://portal.minimal-gaia-x.eu/asset/did:op:05F6562201Dc71B953ba55B9453e0fC688Ca8CA9

The Self-Descriptions can also be retrieved through a custom resolver (GUI and API), as seen here: https://portal.minimal-gaia-x.eu/verify?did=did:op:05F6562201Dc71B953ba55B9453e0fC688Ca8CA9 This also includes real-time verification.

The Self-Descriptions are also checked and metadata is derived from them to be displayed in the frontend which can be seen in the catalogue: https://catalogue.minimal-gaia-x.eu/ Verification and Trust Assessment can be done on-demand in real-time and in a decentralized manner.

Self-Descriptions can be published as RAW self-descriptions on-chain or as URL off-chain, depending on the preferene of the consumer via publish: https://portal.minimal-gaia-x.eu/publish 

Currently we have "two layers" of self-descriptions in the metadata, it should be possible to bring these two layers closer together and to integrate the Ocean-specific attributes in the Gaia-X Self-Descriptions to drive alignment and interoperability of the stack with other solutions that will adapt the same metadata standards. 

Utility: Enable consumers to verify the identity and service composition on demand and in real-time according to the principle of Compliance by Automation or "Don't Trust, Verify".
