### ISSUE TITLE
DID:OP resolvable with Uniresolver

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#163]
DID:OP resolvable with Uniresolver.
DID:OP can’t be resolved with Uniresolver to retrieve the public keys and to validate signatures. This would help with building trust in the Ocean stack and open doors for more interoperability with other solutions.

**Comment by kaimeinke** [comment]
Currently DID:OP cannot be resolved through the Uniresolver https://dev.uniresolver.io/ , see https://github.com/decentralized-identity/universal-resolver which is a drawback when it comes to adoption of the DID-Method by other developers and projects. We propose to make DID:OP resolvable to integrate better with the work of the DIF and other projects and open-source communities working on interoperability. 

Utility: Helps with adoption, acceptance and interoperability.
