### ISSUE TITLE
Enable database access

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#166]
Enable database access.
Ocean offers no means to access a database which is a very common requirement for many use cases. This is top of the list on many talks and should build on some standard APIs/query languages.

**Comment by alexcos20** [comment]
- [ ] define SQL types (Ie:  mysql, postgresql, oracle, etc)
Then for each type:
- [ ] define DDO files object (auth, query, params)
- [ ] integrate support in Provider (maybe https://www.sqlalchemy.org/)
- [ ] integrate it in market
