### ISSUE TITLE
KYC/KYB integration

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#167]
KYC/KYB integration - classic or identity NFT
KYC/KYB integration is a must for any regulatory compliant market in the EU. Without this feature, it will be very difficult to start any discussion on pools or even normal crypto-based consumption.

**Comment by kaimeinke** [comment]
KYB/KYC integration is critical to align with Travel Rule, AML and financial regulation everywhere in the world. This is also a mandatory feature outside the Gaia-X world and it helps to enable trust in service providers, services and consumers.

We propose to adopt SSI/VCs for this matter or an identity NFT (without any personal information). This can be done by accepting Gaia-X Credentials or any other KYC / KYB solution. The challenge however is to accept these credential across platforms, not only in ONE isolated portal. For this reason it is very appealing to integrate the Gaia-X identity ecosystem early as it will be accepted across Europe and enable a large group of participants to rely on the same identity standard without lock-in in just ONE identity solution or just one identity provider. 

Participant Credentials in combination with REGO policies and verifiers can be used fully self-sovereign in a decentralized way and are in line with the requirements, if a Trust Anchor identifies the legal or natural person. 

Utility: Compliance and increased adoption as the market cannot scale without a federated identity solution. From our perspective there is no reason to wait for this as participants will flock to compliant markets first. Current events show very much how much this increase in trust might help.
