### ISSUE TITLE
Allow parametrization of C2D algorithms

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#168]
Allow parametrization of C2D algorithms.
Algorithms need the ability to dynamically pass parameters to the model in order to yield useful results. This is a requirement for advanced AI/ML applications we currently do not satisfy. To change the model, a new algorithm has to be published, which is very inconvenient.

Source: DeltaDAO

**Comment by calina-c** [comment]
Could we use algouserdata somehow?

**Comment by mihaisc** [comment]
This is already in the code. https://docs.oceanprotocol.com/references/provider/#post-apiservicescompute   `algorithm.algocustomdata: Json object, algorithm custom parameters (optional)` . If this is related to the market then it's not relevant for now.

**Comment by kaimeinke** [comment]
We are aware of the availability in the code and we find it highly relevant to provide working examples in the frontend and use cases for this.
