### ISSUE TITLE
Enable alternative payment methods

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#169]
Enable alternative payment methods.
The volatile token adds a significant barrier to adoption. Integration of alternative payment methods (credit card, invoice, etc.) will help to separate concerns and to free the core value proposition of the data access token and logging token, which is desired by many who fear the risk of holding volatile tokens.

Source: DeltaDAO

**Comment by kaimeinke** [comment]
A first version of a stripe integration has already been done using the stripe API. https://mvg-stripe-demo-deltadao.netlify.app/

This enables users to interact with the market without the need and barrier to acquire and hold tokens they do not need for consumption.

This is close to enabling a custodian solution as regulatory firewall against Travel Rule, AML and other potential risks for market providers, service providers and also to protect consumer against volatility. 

This can be driven until total abstraction of the underlying DLT-layer and might be preferable in terms of adoption as most users should care about the utility of the data services and not about the "pleasure" to sign various transactions and take care of key management etc.

This is NOT against a non-custodial approach, but it removes friction and adds user experience for those who care a bit less about having full control. User that prefer full control can still user the classic approach and go through the interactions, be we know from experience that this is a major barrier for users and will dramatically help with user retention and useability.
