### ISSUE TITLE
Social interaction

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#171]
Allow social interaction next to the market (discussion of data sets, algorithms, data/algo bounties). Compare to https://www.data.gouv.fr/fr/ (Business, Applications)
Discussion of data sets, algorithms, data/algo bounties are an advantage of an open data market that we should further utilize. At least a simple comment and rate function to ask public questions about a data set and rate it should be implemented.

**Comment by kaimeinke** [comment]
There is not much to add here except that the current data bounty approach is very much in line with this. This proposal integrated the documentation and social layer in the marketplace frontend to have less media breaks and to enable more seamless and easy discovery of implementations.

A very good example for this is: https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/ where you can immediately discover how the data and logic has been reused to create "data products" which is the only thing that matters in the end. Utility.

![image](https://user-images.githubusercontent.com/59994024/178765577-3bba7ddb-5427-4ff4-a75e-d0a945f538b1.png)

**Comment by mihaisc** [comment]
Who moderates the comments?

**Comment by kaimeinke** [comment]
As this is not a decentralized approach and just a classical Web2 service the responsible party is the platform provider / hoster of this website. 

Basically the same as with Discord but with a dedication towards implementation and reuse.

This can later be extended towards a decentralized feed / stream as Web3 solution  to be picked up and filtered by portals, depending on which services they choose to cater to their target group. Relevant streams can be identified and filtered based on the DIDs of the service, so a large part can be automated in line with the lifecycle management.
