### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#172]
Better documentation will remove friction to adoption (as usual).
Documentation is helpful to driver technical adoption leading to more potential contributors to the ecosystem. Technical adoption and prototyping also mean more insights into the advantages of the ocean tech stack. Enhanced documentation and tutorial posts (blog, video, StackOverflow, Github, etc.) would help here.

Source: DeltaDAO

**Comment by jamiehewitt15** [comment]
I'm closing this as we've now launched the new version of the docs. Any specific issues or enhancements for the docs should be raised in the [docs repo](https://github.com/oceanprotocol/docs)
