### ISSUE TITLE
Gasless integration

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/pm#174]
For the next version we can take a look at https://biconomy.notion.site/Gasless-Integration-Procedure-fc8f7a2aec784d099dfcd3b0920a8b6c to see if this is interesting.

**Comment by jamiehewitt15** [comment]
If we want, we can make gasless interactions without changes to the smart contracts. We could just airdrop enough eth/matic to the user if their wallet is empty when they try to publish/consume. It could also operate like the faucet with limitations based on IP address and account ID

**Comment by trentmc** [comment]
I fully agree with Jamie here.

The problem to solve is "don't want to make customers pay for gas". There are at least two approaches:
1. Gasless txs (meta-txs). As discussed above.
2. Auto-send $ for gas to each account that signs up. Auto top-up top.

(1) is costly, as mentioned above. It also requires re-deploying Ocean contracts, which we should be loathe to do.
(2) is radically simpler, and solves the problem. Enterprise users can do it on their side, they don't need anything from us.

To me, it's a no-brainer to do (2).
And we really really should avoid (1)
