### ISSUE TITLE
Remove Rinkeby and Ropsten

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pm#177]
From rinkeby.etherscan.io: "The Rinkeby testnet explorer will be deprecated and set to read-only on October 5th, 2022. Please migrate your contracts and deploy new ones on Goerli or Sepolia. Read more [here](https://twitter.com/etherscan/status/1569311894279958531)."

From the "here" link (Etherscan twitter): "PSA: The Rinkeby and Ropsten testnet explorers will be deprecated on October 5th, 2022. The explorers will be set to read-only for the foreseeable future and will eventually be sunset. Developers, migrate your contracts and deploy new ones on Goerli or Sepolia!"

Remove Rinkeby and Ropsten
- [x] in contracts repo, remove rinkeby https://github.com/oceanprotocol/contracts/pull/719
- [x] update docs https://github.com/oceanprotocol/docs/pull/1135
- [x] in ocean.py, replace rinkeby with another testnet.
- [x] in ocean.js https://github.com/oceanprotocol/ocean.js/pull/1617
- [x] in aquarius: 
- [x] in provider: 
- [x] take down rinkeby and ropsten subgraphs
- [x] take down rinkeby and ropsten faucets

**Comment by trentmc** [comment]
cc @alexcos20 @AnaLoznianu

**Comment by alexcos20** [comment]
it's already WIP

**Comment by kremalicious** [comment]
closing in favor of #178, which has more complete tracking of all components right now

**Comment by LoznianuAnamaria** [comment]
We should have this issue open as well. On one hand, we are adding Gorli with #178 and on another, we need to remove all over the places rinkeby and ropsten mentions, components, deployments and so on.
