### ISSUE TITLE
Deploy & integrate Goerli network across the stack

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/pm#178]
- [x] https://github.com/oceanprotocol/contracts/issues/683
- [x] in docs repo "networks" section, add goerli https://github.com/oceanprotocol/docs/pull/1134
- [x] https://github.com/oceanprotocol/ocean.js/pull/1613
- [x] https://github.com/oceanprotocol/ocean.js/pull/1614
- [x] subgraph
- [x] aquarius
- [x] provider
- [x] https://github.com/oceanprotocol/market/pull/1704
- [x] faucet
- [x] add funds to the faucet
- [x] ocean.py https://github.com/oceanprotocol/ocean.py/pull/973

Linked issue: https://github.com/oceanprotocol/pm/issues/177

**Comment by md00ux** [comment]
**Aquarius**

Goerli (chain id 5) added to chains list in events:

`$ curl  https://v4.aquarius.oceanprotocol.com/api/aquarius/chains/list`           

```shell
{"1":true,"1285":true,"1287":true,"137":true,"246":true,"3":true,"4":true,"5":true,"56":true,"80001":true}`
```



**Provider**

`$ curl https://v4.provider.goerli.oceanprotocol.com` 

```shell
{"chainId":5,"providerAddress":"0x00c6A0BC5cD0078d6Cd0b659E8061B404cfa5704","serviceEndpoints":{"computeDelete":["DELETE","/api/services/compute"],"computeEnvironments":["GET","/api/services/computeEnvironments"],"computeResult":["GET","
/api/services/computeResult"],"computeStart":["POST","/api/services/compute"],"computeStatus":["GET","/api/services/compute"],"computeStop":["PUT","/api/services/compute"],"create_auth_token":["GET","/api/services/createAuthToken"],"decr
ypt":["POST","/api/services/decrypt"],"delete_auth_token":["DELETE","/api/services/deleteAuthToken"],"download":["GET","/api/services/download"],"encrypt":["POST","/api/services/encrypt"],"fileinfo":["POST","/api/services/fileinfo"],"ini
tialize":["GET","/api/services/initialize"],"initializeCompute":["POST","/api/services/initializeCompute"],"nonce":["GET","/api/services/nonce"],"validateContainer":["POST","/api/services/validateContainer"]},"software":"Provider","versi
on":"1.3.4"}
```



**Ocean Subgraph**

https://v4.subgraph.goerli.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql



**Faucet**

https://faucet.goerli.oceanprotocol.com
Faucet Address - `0xe9caca65047af4f72a72fd000fff33a08a58c9be`

**Comment by LoznianuAnamaria** [comment]
I'll do the docs update

**Comment by mariacarmina** [comment]
I have created the PR on ocean.py which is ready for review https://github.com/oceanprotocol/ocean.py/pull/973

**Comment by LoznianuAnamaria** [comment]
Thank you all for collaborating on this one.
