### ISSUE TITLE
Interview partners for C2D feedback

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#187]
- [ ] prepare questionnaire
- [ ] interview Felt
- [ ] interview Brainstem
- [ ] interview Athena
- [ ] interview Algovera
- [ ] interview DeltaDAO
- [ ] interview DataUnion

**Comment by w1kke** [comment]
We integrated C2D V3 + V4 and also do the backend for Brainstem, WeDataNation, nCight, etc. - if you want to do an interview with DataUnion, please reach out.

**Comment by MBadea17** [comment]
Thanks. I updated the tasks.
