### ISSUE TITLE
Investigate transactions which lead to small gains

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/pm#206]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mihaisc** [comment]
@alexcos20 is this still relevant?

**Comment by LoznianuAnamaria** [comment]
The info here is relevant: https://docs.google.com/spreadsheets/d/1YjOlRl7Fj7Gus51wND_6HC_0nuw9ROiQ6oASkbxAse8/edit?usp=sharing
