### ISSUE TITLE
Goerli will be deprecated in January

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/pm#209]
As Goerli will be [deprecated](https://www.alchemy.com/blog/goerli-faucet-deprecation) in January in Sepolia's favor, we need to adjust our components to reflect this. 
I propose we make the changes in late November. Needed actions
- [x] Remove Goerli from the market 
- [x] Remove Goerli from the status.oceanprotocol.com
- [x] Add Sepolia to status.oceanprotocol.com
- [x] Update docs (Remove Goerli and make sure the tutorials & examples are still working)
- [x] Remove Goerli support from ocean-js
- [ ] Remove Goerli support from ocean-py
- [x] Remove Goerli support from subgraph
- [x] Remove Goerli support from contracts
- [x] Remove Goerli support from Aqua
- [x] Remove Goerli support from the Multichain provider
- [x] Remove Goerli Subgraph
- [x] Remove Faucet
- [x] Validate that template deployments are still working

More? 
cc @mihaisc @alexcos20 

(@alexcos20: Updated to add more repos)

**Comment by mihaisc** [comment]
Make sure various template deployments don't use goerli
Remove faucet
